### ISSUE TITLE
fails on launch

### ISSUE THREAD

**Issue by itchyspacesuit** [jimkang/dependency-parser#3]
```
node_modules/dependency-parser/index.js:14
  function* parse(sentence) {
          ^
SyntaxError: Unexpected token *
```

What's the * doing there? When I remove it I get more failures :S

**Comment by jimkang** [comment]
[It's a generator.](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/function*) Warning: This was an experiment that's not being maintained.
